import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  mainContainer: { flex: 1 },
  containerWrapper: { marginVertical: 150 },
  AccountHolder: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "lightgray",
    marginHorizontal: 10,
    marginVertical: 5,
  },
  penIcon: { marginRight: 15 },
  cardNumber: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "lightgray",
    marginHorizontal: 10,
    alignItems: "center",
    marginVertical: 5,
  },
  cardIcon: { marginRight: 19 },
  inputWrapper: { flexDirection: "row", marginVertical: 5 },
  MMInput: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "lightgray",
    marginHorizontal: 10,
    flex: 1,
  },
  penIcon2: { marginRight: 15 },
  CCVInput: {
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "lightgray",
    marginHorizontal: 10,
    flex: 1,
  },
  saveButton: {
    backgroundColor: "#2B4FFF",
    marginTop: 5,
    marginHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 15,
  },
  buttonText: {
    textAlign: "center",
    color: "white",
    fontSize: 16,
  },
  errorContainer: {
    flexDirection: "row",
    marginHorizontal: 10,
    gap: 5,
    alignItems: "center",
    marginBottom: 5,
  },
  errorText: { color: "red" },
  allInput: { flex: 1 },
});
