import { StyleSheet } from "react-native";
import Colors from "../../Utils/Color";

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  containerWrapper: {
    marginVertical: 120,
  },
  AccountHolder: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "lightgray",
    marginHorizontal: 10,
    marginVertical: 5,
    alignItems: "center",
  },
  usericon: { marginRight: 21 },
  cardNumber: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "lightgray",
    marginHorizontal: 10,
    alignItems: "center",
    marginVertical: 5,
  },
  cardIcon: { marginRight: 19 },
  inputWrapper: { flexDirection: "row", marginVertical: 5 },
  MMNumber: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "lightgray",
    marginHorizontal: 10,
    flex: 1,
  },
  MMIcon: { marginRight: 15 },
  CCVNumber: {
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "lightgray",
    marginHorizontal: 10,
    flex: 1,
  },
  zipCodeContainer: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "lightgray",
    marginHorizontal: 10,
    marginVertical: 5,
  },
  penIcon: { marginRight: 15 },
  paymentButton: {
    backgroundColor: "#2B4FFF",
    marginTop: 5,
    marginHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 15,
  },
  paymentText: {
    textAlign: "center",
    color: "white",
    fontSize: 16,
  },
  newCardButton: {
    backgroundColor: Colors.NEUTRAL.NEUTRAL_WHITE,
    marginTop: 10,
    marginHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "#DADADA",
  },
  newCardText: {
    textAlign: "center",
    fontSize: 16,
  },
  errorContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginHorizontal: 10,
    marginBottom: 10,
  },
  errorText: { color: "red" },
  allInput: { flex: 1 },
});
